### ISSUE TITLE
Debugger popup menu save doesn't update Debugger's world view

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Rowan#127]
If you are in a debugger, and edit the method and save using the method contents pane pop up save menu item, the save doesn't effect the debugger.  The change is in the system browser, but the debugger itself continues to believe in the original, wrong version.  You can click to different contexts and back and you'll see the orginal version; and with run you run back into the same bad code that you fixed. 

However, if you use the Window's menu bar file menu, you can make changes that persist in the debugger. 

Marking this as alpha, but if it's too late to fix we might mention at least mention it somewhere, it looks broken but the workaround is easy.

**Comment by ericwinger** [comment]
I believe ctrl-s works as well. Let me look into it.

**Comment by dalehenrich** [comment]
looks like this is addressed
