### ISSUE TITLE
Get stack trace after going into debugger

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Rowan#140]
If you open the debugger instead of using the copy stack button on the walkback, It is Too Late.  You can't get the stack (other than maybe taking a screenshot).   This seems like something we might need customers to do a lot.  It's pretty natural to open a debugger and see if you did something stupid before bothering about getting the stack.

Better, if there was some smalltalk code you could execute or something to get more detailed stacks.

**Comment by dalehenrich** [comment]
addressed
