### ISSUE TITLE
Expected behavior for classes compiled outside Rowan?

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Rowan#143]
What should the expected behavior be if a user compiles a class outside of Rowan? 

e.g. In a workspace, a user sends `subclass:instVarNames:...` 

Should we prevent this from happening?  Only put a warning in the release notes? Is it already handled? 

Assigning to @dalehenrich for suggestions.

**Comment by dalehenrich** [comment]
Good point ... right now, we say "don't do this" ... in the long term we may decide to modify all of the dangerous rowan messages to include a Notification that signals an error if Rowan is "turned on" and proceeds if Rowan is "turned off".

**Comment by dalehenrich** [comment]
With the completion of #364, the notifications are in place
