### ISSUE TITLE
Jadeite report multiple-component versions string

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Rowan#148]
My expectation is to number alphas 1, 2, 3, 4, etc (per usual GemTalk pattern).  The numbers of the rowan (0.0.2-alpha) and jadeite (Alpha1.0) subcomponent releases are different from each other... and neither match the alpha number (1). However, there's nothing internally to indicate if it's alpha 1 or 2, for example; and it would require some sleuthing to figure out what you have and which alpha it was related to.  

If we have a menu item that the customer can use (after login, so the Rowan version can be detected), that returns something like this:
   'Jadeite Alpha1.0 and Rowan 0.0.2-alpha'
Then we can put those two version numbers in the docs... giving everyone an easy way to correlate.

I can get the Rowan tag 'v0.0.2-alpha', using 
   git describe --abbrev=0 --tags

**Comment by dalehenrich** [comment]
I think version issues are resolved
