### ISSUE TITLE
Leftover Jadeite pegging a CPU

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Rowan#156]
Cleaning up processes in task list and found 2 Jadeite instances each using most of a CPU (22-24 on 4-cpu system).  No visible Jadeite windows to be seen. These are from the Alpha2 release Jadeite.  Nothing relevant in Jadeite.ERRORS file.

I used to see similar hangs with 3.1.x libraries and VW... but that problem (42885 and 42456) was fixed in 3.2.x, so this is a variant, new, or a peculiarity of Dolphin.  Possibly my sequence of closing windows. 

Assigning to myself to gather for more information... I'm sure this isn't enough for Eric to look into.

**Comment by dalehenrich** [comment]
think this is fixed now
