### ISSUE TITLE
When a subclass hierarchy is versioned, superclass display drop-down refuses to coorperate

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Rowan#161]
I created a subclass hierarchy TestOne, TestTwo, TestThree each with methods.  The drop down towards the upper right of the classes browser allows me to determine how far up the superclass sequence to display methods.

If I add an instance variable to TestOne, it recompiles and versions each class.  But now when I have TestThree selected, and pick TestOne or TestTwo in the upper right drop down... it always bounces back to TestThree.  I can up to Object, and then I'll see the methods in the intermediate classes as well as Object methods. 

There's some other peculiar behavior but this is to start on.

This is in packages view, and not cleared up by committing to GemStone.

**Comment by dalehenrich** [comment]
@LisaAlmarode @ericwinger ... I believe that this has been addressed long ago
