### ISSUE TITLE
Need test coverage for changes to package and project properties ...

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/Rowan#180]
Currently we have a `halt` in this branch of RwGsImagePatchVisitor>>visitPackageModification:
https://github.com/dalehenrich/Rowan/blob/70b3dca36abb0427e3ccf14640b53144c1e22271/rowan/src/Rowan-GemStone-Loader/RwGsImagePatchVisitor.class.st#L291-L299
but no existing tests hit this code ...

As part of Issue #141 work, I plan to remove the class **RwGsPackagePropertiesPatch** as this apparently dead chunk of code is the only reference to the class ... I will replace the reference with an error that references this issue. At the moment **RwGsPackagePropertiesPatch** has no useful code anyway...

Currently the only package property is the name of the package, so when we implement package rename or add another property we may end up needing to implement something here.

**Comment by LisaAlmarode** [comment]
Customer reported this error in HR 9847.  They are seeing a problem using Jadeite in creating a class definition, and in topaz get the following stack


Reading /home/dbod/rowan_projects_alpha8/StoreExport/rowan/sources/GS_DBODomainInvestigationObjects/DBOSendMessageAction.class.st
ERROR 2318 , a UserDefinedError occurred (error 2318), reason:halt, internal error - unexpected non-empty project properties modification. See Issue #180 (UserDefinedError)
topaz 1> stack
==> 1 UserDefinedError (AbstractException) >> _signalWith: @5 line 25
    receiver a UserDefinedError occurred (error 2318), reason:halt, internal error - unexpected non-empty project properties modification. See Issue #180
    inCextensionArg nil
    res nil
(skipped 1 evaluationTemps)
2 UserDefinedError (AbstractException) >> signal @2 line 47
    receiver a UserDefinedError occurred (error 2318), reason:halt, internal error - unexpected non-empty project properties modification. See Issue #180
(skipped 2 evaluationTemps)
3 RwGsImagePatchVisitor (Object) >> error:      @6 line 7
    receiver aRwGsImagePatchVisitor
    messageString internal error - unexpected non-empty project properties modification. See Issue #180
(skipped 2 evaluationTemps)
4 RwGsImagePatchVisitor >> visitProjectModification: @22 line 19
    receiver aRwGsImagePatchVisitor
    aProjectModification aRwProjectModification
    propertiesModification aRwPropertiesModification
(skipped 2 evaluationTemps)
5 RwProjectModification >> acceptVisitor:       @2 line 3
    receiver aRwProjectModification
    aVisitor aRwGsImagePatchVisitor
(skipped 2 evaluationTemps)
6 [] in  ExecBlock1 (RwGsImagePatchVisitor) >> visitProjecteSetModification: @2 line 4
    self aRwGsImagePatchVisitor
    receiver anExecBlock1
    each aRwProjectModification
    self aRwGsImagePatchVisitor
(skipped 3 evaluationTemps)
7 Dictionary >> do:                             @8 line 12
    receiver aDictionary
    aBlock anExecBlock1
    i nil
    anAssoc anAssociation
    i 1
(skipped 4 evaluationTemps)
8 RwGsImagePatchVisitor >> visitProjecteSetModification: @3 line 4
    receiver aRwGsImagePatchVisitor
    aProjectSetModification aRwProjectSetModification
    self aRwGsImagePatchVisitor
(skipped 3 evaluationTemps)
9 RwProjectSetModification >> acceptVisitor:    @2 line 3
    receiver aRwProjectSetModification
    aVisitor aRwGsImagePatchVisitor
(skipped 2 evaluationTemps)
10 RwGsImagePatchVisitor >> visit:               @2 line 3
    receiver aRwGsImagePatchVisitor
    aPackageSetModification aRwProjectSetModification
(skipped 2 evaluationTemps)
11 RwGsImage class >> applyModification:visitorClass:instanceMigrator: @4 line 5
    receiver RwGsImage
    aProjectSetModification aRwProjectSetModification
    visitorClass RwGsImagePatchVisitor
    instanceMigrator aRwGsInstanceMigrator
    newClassVersionPatchSet nil
    patchSet nil
    aProjectSetModification aRwProjectSetModification
    visitor aRwGsImagePatchVisitor
(skipped 2 evaluationTemps)
12 RwGsImage class >> applyModification:instanceMigrator: @8 line 13
    receiver RwGsImage
    aProjectSetModification aRwProjectSetModification
    instanceMigrator aRwGsInstanceMigrator
    visitorClass nil
(skipped 4 evaluationTemps)
13 RwPrjLoadTool >> _loadProjectSetDefinition:instanceMigrator: @17 line 19
    receiver aRwPrjLoadTool
    projectSetDefinitionToLoad aRwProjectSetDefinition
    instanceMigrator aRwGsInstanceMigrator
    loadedProjectInfo aDictionary
    self aRwPrjLoadTool
    msg nil
    diff aRwProjectSetModification
    loadedProjectSet aRwProjectSetDefinition
    projectSetDefinitionToLoad aRwProjectSetDefinition
(skipped 3 evaluationTemps)
14 [] in  ExecBlock0 (RwPrjLoadTool) >> _doProjectSetLoad:instanceMigrator:originalProjectSet:processedClassNames: @2 line 4
    self aRwPrjLoadTool
    receiver anExecBlock0
    instanceMigrator aRwGsInstanceMigrator
    projectSetDefinition aRwProjectSetDefinition
    self aRwPrjLoadTool
(skipped 4 evaluationTemps)
15 ExecBlock0 (ExecBlock) >> on:do:              @3 line 42
    self aRwPrjLoadTool
    receiver anExecBlock0
    exceptionSelector RwExistingVisitorAddingExistingClassNotification
    handlerBlock anExecBlock
    fastPath true
(skipped 1 evaluationTemps)
16 RwPrjLoadTool >> _doProjectSetLoad:instanceMigrator:originalProjectSet:processedClassNames: @2 line 6
    receiver aRwPrjLoadTool
    projectSetDefinition aRwProjectSetDefinition;   instanceMigrator aRwGsInstanceMigrator;   originalProjectSet aRwProjectSetDefinition
    processedClassNames aSet;   processedClassNames aSet;   originalProjectSet aRwProjectSetDefinition
    instanceMigrator aRwGsInstanceMigrator;   copiedProjectSetDef nil;   self aRwPrjLoadTool;   (skipped 6 evaluationTemps)

17 RwPrjLoadTool >> loadProjectSetDefinition:instanceMigrator: @3 line 7
    receiver aRwPrjLoadTool
    projectSetDefinition aRwProjectSetDefinition
    instanceMigrator aRwGsInstanceMigrator
(skipped 5 evaluationTemps)
18 RwPrjLoadTool >> loadProjectSetDefinition:    @4 line 4
    receiver aRwPrjLoadTool
    projectSetDefinitionToLoad aRwProjectSetDefinition
(skipped 3 evaluationTemps)
19 RwPrjLoadTool >> loadProjectFromSpecUrl:      @10 line 6
    receiver aRwPrjLoadTool
    fileUrlOrString file:/home/dbod/rowan_projects_alpha8/StoreExport/rowan/specs/StoreExport.ston
    projectSetDefinitionToLoad aRwProjectSetDefinition
    projectDefinition aRwProjectDefinition
(skipped 2 evaluationTemps)
20 Executed Code                                 @4 line 2
    receiver nil
(skipped 2 evaluationTemps)
21 GsNMethod class >> _gsReturnToC               @1 line 1
    receiver GsNMethod

**Comment by dalehenrich** [comment]
Just a note that this error may have occurred after other odd things were going on in the image ... the only property in a project is it's name ...

**Comment by LisaAlmarode** [comment]
In Alpha 8, I can reproduce this error message easily by just adding a package.  What's non-empty is that the propertiesModification includes the spec, and the specs are different... perhaps since the initial load is from the spec in Rowan and the re-load is from the project itself? 

I suggest "Unexpected state in a Project modification; see Issue #180"

or "Unexpected state in a Project modification, usually the side-effect of some other problem; see Issue #180"

**Comment by dalehenrich** [comment]
in V2.0, the class RwGsPackagePropertiesPatch is gone; commit 3d9db48 replaces the non-specific error with a better error message; there is at least one test added as well
