### ISSUE TITLE
GemStone error: ArgumentError occurred (error 2283) and Jade Error: Index 1 out of bounds

### ISSUE THREAD

**Issue by ablakeman** [GemTalk/Rowan#183]
It's not entirely clear how I got to this point, but Dale suggested that I submit this anyway.  

1. I had a debugger window open and in the background.
2. In a browser window, I went to methods -> Browse implementors of..
3. I typed 'register: '

I then got the attached walkback and jade error, seemingly at the same time.  I've followed these steps again trying to reproduce the bug, but so far I've been unsuccessful.

![bug1](https://user-images.githubusercontent.com/16963117/40023294-6f9b0b4c-577f-11e8-9702-873e0f97d321.png)

**Comment by dalehenrich** [comment]
There are multiple stacks inthe file and the next stack from the top has this timestamp and error message that does line up with one of the errors: 
```
11:37:02 AM, 5/14/2018: Index 1 is out of bounds
```

**Comment by dalehenrich** [comment]
think this is addressed by now
