### ISSUE TITLE
Add "compile outside Rowan" switch

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Rowan#205]
There are times when it is necessary to compile outside of Rowan, e.g. changing a base class currently. 

There is a global `rowanCompile` in the code which controls that. We should add a switch to make it easier to turn that on or off. Appropriate warnings should be included as any compile outside Rowan is not tracked.

**Comment by dalehenrich** [comment]
When work in Issue #364 is integrated into Jadeite, this feature won't be needed
