### ISSUE TITLE
Primitive Behavior>>new: failed (0)

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Rowan#226]
I am creating a project programmatically and adopting a couple of symbol dictionaries into packages.  

In the PLB, with my new not-git-committed-project selected, I tried clicking on changes and got an error dialog, saying: "Primitive Behavior>>new: failed (0)",
with the following in my jadeite. errors log.  It's looking at some of the code that was adopted and with bad string offset args.  

This is with jadeite 2.0.1 and rowan branch issue_208 commit  daf5168.

************************** Dolphin Virtual Machine Dump Report ***************************

16:20:31 PM, 6/13/2018: Primitive Behavior>>new: failed (0)

*----> VM Context <----*
Process: {07220210:size 490 words, suspended frame 0722092D, priority 5, callbacks 1
last failure 2:nil, FP control 3, thread 00000000}
Active Method: SessionManager>>logError:
IP: 028A8CB9 (9)
SP: 07220A98
BP: 07220A6C (520)
ActiveFrame: {07220A70: cf 07220A51, sp 07220A88, bp 07220A6C, ip 5, JadeSessionManager(SessionManager)>>logError:}
	receiver: a JadeSessionManager
	arg[0]: a Error

New Method: VMLibrary>>dump:path:stackDepth:walkbackDepth:
Message Selector: dump:path:stackDepth:walkbackDepth:

*----> Stack Back Trace <----*
{07220A70: cf 07220A51, sp 07220A88, bp 07220A6C, ip 5, JadeSessionManager(SessionManager)>>logError:}
	receiver: a JadeSessionManager
	arg[0]: a Error

{07220A50: cf 07220A31, sp 07220A64, bp 07220A4C, ip 3, JadeSessionManager(SessionManager)>>unhandledException:}
	receiver: a JadeSessionManager
	arg[0]: a Error

{07220A30: cf 07220A11, sp 07220A44, bp 07220A2C, ip 3, JadeSessionManager(SessionManager)>>onUnhandledError:}
	receiver: a JadeSessionManager
	arg[0]: a Error

{07220A10: cf 072209F5, sp 07220A24, bp 07220A10, ip 5, Error>>defaultAction}
	receiver: a Error

{072209F4: cf 072209C1, sp 07220A08, bp 072209DC, ip 55, Error(Exception)>>_propagateFrom:}
	receiver: a Error
	arg[0]: a ExceptionHandler
	stack temp[0]: nil
	stack temp[1]: a ExceptionHandler
	stack temp[2]: nil
	stack temp[3]: a Process('Main' base 07220000 [ACTIVE] in SessionManager>>logError: sp=00000000 ip=4 list=0F010010)
	stack temp[4]: nil

{072209C0: cf 072209A1, sp 072209D4, bp 072209BC, ip 6, Error(Exception)>>_propagate}
	receiver: a Error
	stack temp[0]: nil

{072209A0: cf 07220985, sp 072209B4, bp 072209A0, ip 13, Error(Exception)>>signal}
	receiver: a Error

{07220984: cf 07220965, sp 07220998, bp 07220980, ip 5, Error(Exception)>>signal:}
	receiver: a Error
	arg[0]: 'Primitive Behavior>>new: failed (0)'

{07220964: cf 07220945, sp 07220978, bp 07220960, ip 5, Error class(Exception class)>>signal:}
	receiver: Error
	arg[0]: 'Primitive Behavior>>new: failed (0)'

{07220944: cf 07220925, sp 07220958, bp 07220940, ip 4, String class(Object)>>error:}
	receiver: String
	arg[0]: 'Primitive Behavior>>new: failed (0)'

{07220924: cf 07220905, sp 07220938, bp 07220920, ip 17, String class(Object)>>primitiveFailed}
	receiver: String
	stack temp[0]: a Process('Main' base 07220000 [ACTIVE] in SessionManager>>logError: sp=00000000 ip=4 list=0F010010)

{07220904: cf 072208E5, sp 07220918, bp 07220900, ip 14, String class(Behavior)>>new:}
	receiver: String
	arg[0]: -18

{072208E4: cf 072208C5, sp 072208F8, bp 072208E0, ip 3, String class(SequenceableCollection class)>>ofSize:}
	receiver: String
	arg[0]: -18

{072208C4: cf 072208A5, sp 072208D8, bp 072208C0, ip 4, String(SequenceableCollection)>>copyLikeOfSize:}
	receiver: 'VarietyList rwIndexableSubclass: '''VarietySalesStatusList'''\0D\\0A\\09\instVarNames: #(...'
	arg[0]: -18

{072208A4: cf 0722087D, sp 072208B8, bp 07220898, ip 8, String(SequenceableCollection)>>copyFrom:to:}
	receiver: 'VarietyList rwIndexableSubclass: '''VarietySalesStatusList'''\0D\\0A\\09\instVarNames: #(...'
	arg[0]: 80
	arg[1]: 61
	stack temp[0]: -18

{0722087C: cf 07220851, sp 07220890, bp 07220870, ip 49, MCClassDefinition>>initialize:}
	receiver: a MCClassDefinition
	arg[0]: a ReadStream
	stack temp[0]: 79
	stack temp[1]: 62

{07220850: cf 07220829, sp 07220868, bp 07220844, ip 37, MCDefinition class>>fromStream:}
	receiver: MCDefinition
	arg[0]: a ReadStream
	stack temp[0]: $C
	stack temp[1]: MCClassDefinition

{07220828: cf 07220809, sp 0722083C, bp 07220824, ip 4, MCAddition>>initialize:}
	receiver: a MCAddition
	arg[0]: a ReadStream

{07220808: cf 072207E1, sp 0722081C, bp 072207FC, ip 15, MCAddition(MCPatchOperation)>>initialize:session:}
	receiver: a MCAddition
	arg[0]: a ReadStream
	arg[1]: a GciSession
	stack temp[0]: '50073857'

{072207E0: cf 072207B1, sp 072207F4, bp 072207D0, ip 38, MCPatchOperation class>>fromStream:session:}
	receiver: MCPatchOperation
	arg[0]: a ReadStream
	arg[1]: a GciSession
	stack temp[0]: $A
	stack temp[1]: MCAddition

{072207B0: cf 07220789, sp 072207C8, bp 072207A4, ip 26, RowanPatch(MCPatch)>>initialize:session:}
	receiver: a RowanPatch
	arg[0]: '50074369\09\closest ancestor vs. loaded\0A\A\09\50074113\09\C\09\Object rwSubclass: '''Customer...'
	arg[1]: a GciSession
	stack temp[0]: a ReadStream

{07220788: cf 07220761, sp 0722079C, bp 07220780, ip 6, RowanPatch class(GsObject class)>>fromString:session:}
	receiver: RowanPatch
	arg[0]: '50074369\09\closest ancestor vs. loaded\0A\A\09\50074113\09\C\09\Object rwSubclass: '''Customer...'
	arg[1]: a GciSession

{07220760: cf 07220739, sp 07220778, bp 0722075C, ip 88, [] in RowanProjectService>>changes}
	receiver: a RowanProjectService
	arg[0]: 'Tomatoes3'

{07220738: cf 07220715, sp 07220754, bp 07220730, ip 11, OrderedCollection>>do:}
	receiver: a OrderedCollection
	arg[0]: [] @ 9 in RowanProjectService>>changes
	stack temp[0]: 2

{07220714: cf 072206F9, sp 07220728, bp 07220714, ip 95, RowanProjectService>>changes}
	receiver: a RowanProjectService
	env temp[0]: a WriteStream
	env temp[1]: a RowanPatch
	env temp[2]: a JadeServerReadStream
	env temp[3]: '26\0A\changesInPackage\0A\50074369\09\closest ancestor vs. loaded\0A\A\09\50074113\09\C\09\Object rwS...'

{072206F8: cf 072206D5, sp 0722070C, bp 072206F0, ip 19, RowanProjectListPresenter>>projectChanges}
	receiver: a RowanProjectListPresenter
	stack temp[0]: a RowanProjectService
	stack temp[1]: nil

{072206D4: cf 072206B5, sp 072206E8, bp 072206D0, ip 4, Symbol>>forwardTo:}
	receiver: projectChanges
	arg[0]: a RowanProjectListPresenter

{072206B4: cf 07220695, sp 072206C8, bp 072206B0, ip 4, CommandDescription>>performAgainst:}
	receiver: a CommandDescription
	arg[0]: a RowanProjectListPresenter

{07220694: cf 07220671, sp 072206A8, bp 07220694, ip 14, [] in Command>>value}
	receiver: a Command

{07220670: cf 07220651, sp 07220684, bp 0722066C, ip 18, BlockClosure>>ifCurtailed:}
	receiver: [] @ 0 in nil
	arg[0]: [] @ 17 in Command>>value

{07220650: cf 0722062D, sp 07220664, bp 07220648, ip 3, BlockClosure>>ensure:}
	receiver: [] @ 11 in Command>>value
	arg[0]: [] @ 17 in Command>>value
	stack temp[0]: nil

{0722062C: cf 07220611, sp 07220640, bp 0722062C, ip 22, Command>>value}
	receiver: a Command

{07220610: cf 072205F1, sp 07220624, bp 0722060C, ip 30, ShellView>>performCommand:}
	receiver: a ShellView
	arg[0]: a Command

{072205F0: cf 072205D1, sp 07220604, bp 072205EC, ip 4, RowanProjectListShell(Shell)>>performCommand:}
	receiver: a RowanProjectListShell
	arg[0]: a Command

{072205D0: cf 072205AD, sp 072205E4, bp 072205C8, ip 4, RowanProjectListShell>>performCommand:}
	receiver: a RowanProjectListShell
	arg[0]: a Command
	stack temp[0]: nil

{072205AC: cf 07220585, sp 072205C0, bp 072205A0, ip 10, CommandQuery>>perform}
	receiver: a CommandQuery
	stack temp[0]: a Command
	stack temp[1]: nil
	stack temp[2]: a RowanProjectListShell

{07220584: cf 07220561, sp 07220598, bp 0722057C, ip 8, DelegatingCommandPolicy(CommandPolicy)>>route:}
	receiver: a DelegatingCommandPolicy
	arg[0]: a CommandDescription
	stack temp[0]: a CommandQuery

{07220560: cf 07220539, sp 07220574, bp 0722055C, ip 15, [] in ListView(View)>>onCommand:}
	receiver: a ListView

{07220538: cf 07220519, sp 0722054C, bp 07220534, ip 18, BlockClosure>>ifCurtailed:}
	receiver: [] @ 0 in nil
	arg[0]: [] @ 17 in Cursor>>showWhile:

{07220518: cf 072204F5, sp 0722052C, bp 07220510, ip 3, BlockClosure>>ensure:}
	receiver: [] @ 11 in View>>onCommand:
	arg[0]: [] @ 17 in Cursor>>showWhile:
	stack temp[0]: nil

{072204F4: cf 072204CD, sp 07220508, bp 072204E8, ip 27, Cursor>>showWhile:}
	receiver: a Cursor
	arg[0]: [] @ 11 in View>>onCommand:
	stack temp[0]: a Cursor
	stack temp[1]: a ExternalHandle(00010007)

{072204CC: cf 072204A9, sp 072204E0, bp 072204C4, ip 17, ListView(View)>>onCommand:}
	receiver: a ListView
	arg[0]: a CommandDescription
	stack temp[0]: nil

{072204A8: cf 07220475, sp 072204BC, bp 07220490, ip 19, ListView(View)>>wmCommand:wParam:lParam:}
	receiver: a ListView
	arg[0]: 273
	arg[1]: 17659
	arg[2]: 0
	stack temp[0]: 17659
	stack temp[1]: a CommandDescription
	stack temp[2]: nil

{07220474: cf 07220445, sp 07220488, bp 07220460, ip 23, ListView(View)>>dispatchMessage:wParam:lParam:}
	receiver: a ListView
	arg[0]: 273
	arg[1]: 17659
	arg[2]: 0
	stack temp[0]: nil
	stack temp[1]: wmCommand:wParam:lParam:

{07220444: cf 07220411, sp 07220458, bp 07220434, ip 69, [] in InputState>>wndProc:message:wParam:lParam:cookie:}
	receiver: nil

{07220410: cf 072203E9, sp 07220424, bp 0722040C, ip 18, BlockClosure>>ifCurtailed:}
	receiver: [] @ 0 in nil
	arg[0]: [] @ 79 in InputState>>wndProc:message:wParam:lParam:cookie:

{072203E8: cf 072203AD, sp 07220404, bp 072203D0, ip 84, InputState>>wndProc:message:wParam:lParam:cookie:}
	receiver: a InputState
	arg[0]: 3934466
	arg[1]: 273
	arg[2]: 17659
	arg[3]: 0
	arg[4]: 818580
	stack temp[0]: a ListView

{072203AC: cf 0722038D, sp 072203C8, bp 072203A8, ip 28, InputState>>pumpMessage:}
	receiver: a InputState
	arg[0]: a MSG

{0722038C: cf 07220361, sp 072203A0, bp 0722037C, ip 18, InputState>>loopWhile:}
	receiver: a InputState
	arg[0]: [] @ 9 in InputState>>mainLoop
	stack temp[0]: a MSG
	stack temp[1]: true
	stack temp[2]: [] @ 50 in JadeSystemBrowserPresenter>>layoutInfo:

{07220360: cf 07220345, sp 07220374, bp 07220360, ip 15, InputState>>mainLoop}
	receiver: a InputState

{07220344: cf 07220329, sp 07220358, bp 07220344, ip 14, [] in InputState>>forkMain}
	receiver: a InputState

{07220328: cf 0722030D, sp 0722033C, bp 07220328, ip 13, ExceptionHandler(ExceptionHandlerAbstract)>>markAndTry}
	receiver: a ExceptionHandler

{0722030C: cf 072202E5, sp 07220320, bp 07220308, ip 22, [] in ExceptionHandler(ExceptionHandlerAbstract)>>try:}
	receiver: a ExceptionHandler

{072202E4: cf 072202C5, sp 072202F8, bp 072202E0, ip 18, BlockClosure>>ifCurtailed:}
	receiver: [] @ 0 in nil
	arg[0]: [] @ 39 in ExceptionHandlerAbstract>>try:

{072202C4: cf 072202A1, sp 072202D8, bp 072202BC, ip 3, BlockClosure>>ensure:}
	receiver: [] @ 17 in ExceptionHandlerAbstract>>try:
	arg[0]: [] @ 39 in ExceptionHandlerAbstract>>try:
	stack temp[0]: nil

{072202A0: cf 07220279, sp 072202B4, bp 07220294, ip 44, ExceptionHandler(ExceptionHandlerAbstract)>>try:}
	receiver: a ExceptionHandler
	arg[0]: [] @ 10 in InputState>>forkMain
	stack temp[0]: nil
	stack temp[1]: a Process('Main' base 07220000 [ACTIVE] in SessionManager>>logError: sp=00000000 ip=4 list=0F010010)
	env temp[0]: nil

{07220278: cf 07220255, sp 0722028C, bp 07220270, ip 7, BlockClosure>>on:do:}
	receiver: [] @ 10 in InputState>>forkMain
	arg[0]: ProcessTermination
	arg[1]: [] @ 13 in BlockClosure>>newProcess

{07220254: cf 00000001, sp 07220268, bp 07220254, ip 17, [] in BlockClosure>>newProcess}
	receiver: [] @ 10 in InputState>>forkMain

<Bottom of stack>

***** End of dump *****

**Comment by dalehenrich** [comment]
I'm guessing that this issue pops up when there are empty packages on disk ... will need to fiddle around to see if this is indeed the case ... I think I've reported a bug on this, but without a reproducible test case these particular errors are difficult to debug, because it is an error in the serialization format used by Jadeite, but because it's a stack from Dolphin, we don't have access to the string (and the strings are hard to find bugs in as welll ...)

**Comment by dalehenrich** [comment]
I assume that this is no longer an issue for Jadeite
