### ISSUE TITLE
permissions for /tmp/commitMessage

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Rowan#257]
Customer is doing Jadeite git commits on the same host, but as different Unix users.  
A Jadeite git commit writes a file /tmp/commitMessage with the permissions -rw-r--r--, and leaves this file in place some if not all the time after completing. 
If a different Unix user attempts to Jadeite git commit, they don't have permission to overwrite this file and the commit operation fails

**Comment by dalehenrich** [comment]
Moving this issue to v2.0.0, because FileSystemGs has support for creating unique /tmpfiles that should be used to address this issue
