### ISSUE TITLE
Reconcile badly broken under some unknown conditions

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Rowan#258]
Reconcile is not behaving as it should, per customer: it works fine for me.  Possibly the initial SETT contents are weird; I have tested with config/specs as I think are generated by SETT and spoofed code, and that also works for me. Pending more information, this is what appears to be happening.  

--- reconcile does not move extension method files out of the package they are in, does not create new packages with the appropriate new names, and the changes to the written config file are minor/version related.

--- For each existing package, reconcile creates a new directory with the same name with .package appended:
   ...rowan/sources/<existingpackagename>.package

These new directories each contain only a single file, properties.ston, with the contents:

{
	"_cypress_copyright" : "This%20work%20is%20protected%20by%20copyright.%20All%20rights%20reserved.",
	"_gs_format" : "Cypress",
	"_gs_strict" : "false" }

--- attempting the load of the reconciled project now does not error but does not load anything.

**Comment by dalehenrich** [comment]
I think that this issue has been resolved ...
