### ISSUE TITLE
Jadeite default project * not reliable

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Rowan#262]
Using Jadeite 2.0.1, if you clone the default git project (RowanSample1), and load it, this project gets a little star next to it that should indicate that it's the default project.

However, if you then go to a system browser and use the menu item Add Package, you get a dialog "No default project has been created.  Please specify in the project list".

So you have to go back to the Project List Browser and use Make Default.  It then has the same star next to it which now is correct.

This obviously not an urgent problem.

**Comment by dalehenrich** [comment]
If this is still an issue, it should be submitted against Jadeite as it seems to be a pure Jadeite issue ..
