### ISSUE TITLE
Source code LFs vs CRs

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Rowan#266]
Customer notes that adopted packages have changed all CARRIAGE_RETURN (ascii hex 0D) characters to LINEFEED (ascii hex 0A).  HR 9873.  This is not high priority but assign to myself to investigate.  

This can have various implications:
- all methods will have different code. An incremental upload would detect that all methods have changes.
- different behavior when such a line feed are in string literals.
Filing out code in TOPAZ seems to always use LINEFEED (ascii hex 0A).

**Comment by dalehenrich** [comment]
I think this issue was addressed
