### ISSUE TITLE
Remove a constraint doesn't "take"

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Rowan#326]
From: @LisaAlmarode

Original issue: 
https://github.com/ericwinger/Jade/issues/44

I verified this fails in a workspace. 

My test case happens to have constraints in the class definition. Removing one or both of the two constraints doesn't have any effect - the definition still shows the constraints. It appears impossible remove constraints.

Creation and modification use the template:

Object rwSubclass: 'Moth'
instVarNames: #( aaa bbb ccc)
classVars: #()
classInstVars: #()
poolDictionaries: #()
category: 'PackageTwoA'
constraints: { { #aaa . String} .
{ #bbb . Integer} }
options: #()

**Comment by ericwinger** [comment]
Per Lisa's comment, constraint changes don't show up in Show Changes list. 
https://github.com/ericwinger/Jade/issues/44#issuecomment-415649837

**Comment by ericwinger** [comment]
Indeed we can. Closing this bug in favor of https://github.com/dalehenrich/Rowan/issues/347

We do have an outstanding issue to display method-level changes. https://github.com/dalehenrich/Rowan/issues/276
However, I didn't see an open issue for anything else specifically on constraints.

**Comment by dalehenrich** [comment]
@ericwinger don't you think we need a "reimplement changes in Jadeite" bug  ... right now we using a hacked up Monticello diffs mechanism that needs to be replaced ... Jadeite should be able to display a RowanProjectModification/RowanPackageModification/RowanClassModifiction/RowanClassExtensionModificaiton/RowanMethodModifcation ... only then would Jadeite be able to properly display all of the changes ...

**Comment by ericwinger** [comment]
After talking with @dalehenrich, retiring this bug in favor of https://github.com/ericwinger/Jade/issues/123 - a more complete solution.

**Comment by dalehenrich** [comment]
After patching Issue #498, the tests for this issue have started to randomly fail ...

**Comment by dalehenrich** [comment]
... turns out that the regression for these tests was caused by the Issue #498 bugfix
