### ISSUE TITLE
cloning RowanSample1 with 'https://github.com/dalehenrich/RowanSample1.git'

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Rowan#336]
I tried cloning RowanSample1 project automatically in a test with an https string:
``'https://github.com/dalehenrich/RowanSample1.git'``

It failed on this rather odd piece of code: 
``client := (Rowan globalNamed: 'ZnClient') new.``

Does Rowan support direct cloning from git hub yet? 
```
a MessageNotUnderstood occurred (error 2010), a UndefinedObject does not understand  #'new'
RwSpecification class >> fromUrl: @23 line 29
RwPrjCloneTool >> cloneSpecUrl:gitRootPath:useSsh: @2 line 4
RowanProjectService >> newGitProject:root:useSsh: @4 line 5
[] in  ExecBlock1 (JadeServer) >> updateFromSton: @9 line 11
Array (Collection) >> do: @5 line 10
JadeServer64bit32 (JadeServer) >> updateFromSton: @7 line 6
GsNMethod class >> _gsReturnToC @1 line 1

**Comment by dalehenrich** [comment]
At the moment, Rowan recognizes the `https:` url, however, the base image does not have `https` download support ... we could do a bit better with having an error to explain this to other users:)

**Comment by dalehenrich** [comment]
BTW, is there a reason you are not using the [sample spec](https://github.com/dalehenrich/Rowan/blob/oscar/samples/RowanSample1.ston) to clone and download RowanSample1

**Comment by ericwinger** [comment]
@dalehenrich I was trying to ensure the project was  automatically loaded in a test. Wasn't sure the best approach.  Ideally, I could run my sunit tests and if the RowanSample1 project was not present, the test would load it. I'm open to ideas when we have more time.

**Comment by dalehenrich** [comment]
I have several tests that reliably clone git repos and I have referred to the specific tests elsewhere ... I believe that [(one) the problems James ran into](https://github.com/ericwinger/Jade/issues/73#issuecomment-414897711) is due the fact that he is the test on a mac - see Issue #344.

**Comment by dalehenrich** [comment]
It is also worth noting that `'https://github.com/dalehenrich/RowanSample1.git'` would not be a proper url argument ...although I am not quite sure which api was used, it was probably used where a spec url was expected ...

**Comment by dalehenrich** [comment]
This is an example of an url that would work if we had https: support: `https://raw.githubusercontent.com/dalehenrich/RowanSample1/master/rowan/specs/RowanSample1.ston`. If you use `wget` to resolve the url, you will see that you get the RowanSample1.ston spec file downloaded
