### ISSUE TITLE
Project stays in loaded projects list after abort

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Rowan#348]
Aborting after loading a project leaves the project in the loadedProjects list. 

```

Rowan image loadedProjects

```
anIdentitySet( aRwGsLoadedSymbolDictProject Rowan, aRwGsLoadedSymbolDictProject Cypress, aRwGsLoadedSymbolDictProject Tonel, aRwGsLoadedSymbolDictProject STON)
```
Rowan projectTools clone
		cloneSpecUrl: 'file:$ROWAN_PROJECTS_HOME/Rowan/samples/RowanSample1.ston'
		gitRootPath: '$ROWAN_PROJECTS_HOME'
		useSsh: true.
Rowan projectTools load loadProjectNamed: 'RowanSample1'
Rowan image loadedProjects. 
```
anIdentitySet( aRwGsLoadedSymbolDictProject RowanSample1, 
 aRwGsLoadedSymbolDictProject Rowan, aRwGsLoadedSymbolDictProject Cypress, aRwGsLoadedSymbolDictProject Tonel, aRwGsLoadedSymbolDictProject STON)
```
System abortTransaction
Rowan image loadedProjects
```
anIdentitySet( aRwGsLoadedSymbolDictProject RowanSample1, <<<---- Project RowanSample1 still in list. 
aRwGsLoadedSymbolDictProject Rowan, aRwGsLoadedSymbolDictProject Cypress, aRwGsLoadedSymbolDictProject Tonel, aRwGsLoadedSymbolDictProject STON)  <

This has side effects such as trying to get the hierarchy of a class in the project. Jadeite gets upset at this. 

``(ClassOrganizer newWithRoot: RowanSample1) hierarchy anIdentityDictionary( #'nil'->aClassSet( Object))``  <<<<<----Notice how RowanSample1 doesn't include itself in the hierarchy class list.

**Comment by dalehenrich** [comment]
This is related to GemTalk/Jadeite#113 ... see [this comment for details](https://github.com/GemTalk/Jadeite/issues/113#issuecomment-416728685)

**Comment by dalehenrich** [comment]
@ericwinger ... this is not reproducing for me ... as I noted in GemTalk/jadeite#113 when you open a new project browser the RowanSample1 project does not show up ... and the project list shows correctly when it is refreshed ...

I'm not sure exactly what you are doing differently to get your results ... both the abort button and `System abort` give me the same results ... only 4 elements in the `Rowan loadedProjects` after abort.
I didn't update to the latest Oscar, but I believe I am using the latest Oscar:
![image](https://user-images.githubusercontent.com/623951/44805376-e0c17480-ab78-11e8-8e32-656cce5515e7.png)

**Comment by dalehenrich** [comment]
Closing for now ... it seems that there was some unexpected committed state
