### ISSUE TITLE
Rowan tests should not stomp on sessionState 3

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Rowan#367]
Jadeite depends on knowing where a JadeServer subclass instance is. It has (always?) put it in session state 3 in the Jadeite client method `postLoginAs:useSocket:`. 

After I run the ``RwRowanProjectIssuesTest`` test suite, I see that ``System _sessionStateAt: 3`` returns false instead of an instance of JadeServer. It shouldn't but I am not sure what is changing it. 

I am adding a server test that checks this. ``JadeServerTest>>test_jadeServerHeldInSessionState``

**Comment by dalehenrich** [comment]
I cannot find any senders of #sessionStateAt:put:  or #_sessionStateAt:put: in the image and this is the list of #__sessionStateAt:put: senders ... none of which are Rowan methods:
![image](https://user-images.githubusercontent.com/623951/46635787-6e926700-cb0a-11e8-894b-1aea36d5d570.png)

**Comment by dalehenrich** [comment]
you don't mention how the session state gets set, but if you look at #sessionState:, 39 is added to the value, so perhaps you should be checking `sessionStateAt: 42`? Coincidence? perhaps not:)

**Comment by ericwinger** [comment]
> you don't mention how the session state gets set

@dalehenrich Jadeite sets session state 3 in a client method which does a server call. 

I did a search for something in Rowan setting session state but didn't find anything either. I would be curious if you see the same problem with this reproduction case:

- Login to a server with a new session from Jadeite. 
- Inspect ``System _sessionStateAt: 3``. It should be an instance of JadeServer subclass. 
- Run the ``RwRowanProjectIssuesTest `` tests. 
- Inspect ``System _sessionStateAt: 3``.  It is now ``false`` at least for me. 

In the meantime, I'll dig around in Jadeite for suspicious code. Perhaps I'll find the meaning of life. ;)

**Comment by dalehenrich** [comment]
Perhaps you should read the docs for the gci call ... because either 39 or 20 is added to the argument depending upon which getter you are using ... I know you are getting false ... but Rowan is doing anything so the most likely explanation is that you are looking at 23 when your should be looking at 42 or vice version ... I would expect to see the result you are seeing, but that doesn't mean anything... there are no explicit senders of _sessionStateAt:put: that I can find, but it _is_ possible that Jade/Jadeite is using a reserved slot that is being used by GemStone for another purpose ... unset values return nil ... so perhaps you should read the gci docs for the call used by jadeite and find out exactly which clot is being st ... if it is actually less than slot 39, then it is definitely wrong ...

**Comment by ericwinger** [comment]
Code reading reveals that _sessionStateAt:* is deprecated. That method adds 20. 
The comment says to use sessionStateAt:* which adds 39. 

I'll see what it takes to have Jadeite use the latter and see what happens.

**Comment by ericwinger** [comment]
The problem was not in Rowan code. Jadeite was using the wrong api to set session state thus putting the jade server in a slot potentially reusable by GemStone. 

A more detailed involves three methods that set session state - 
1. ``sessionStateAt:put:`` - public method which offsets the parameter by 39. 
2. ``_sessionStateAt:put:``  - deprecated method which offsets the parameter by 20. 
3. ``__sessionStateAt:put:`` - primitive method where no offset done. 

Jadeite was sending deprecated method ``_sessionStateAt:`` when it should have been sending primitive method ``__sessionStateAt:``. The deprecated method put the JadeServer instance within "Gemstone's area" and was being overwritten by GemStone causing this bug. The primitive puts the JadeServer instance truly at slot 3, not 42. Although Slot 3 is reserved, the reservation is for Topaz. In discussions with James that slot is safe because Topaz is not used during a Jadeite session. It also avoids conflicting with any application code that uses session states above 39.

The effects turned out to be relatively benign except for the new tests added which explicitly look for a JadeServer instance in the session state collection. It was benign because Jadeite holds onto the instance explicitly and doesn't do a session state lookup. 

Fix will be in Oscar 3.0.41.
