### ISSUE TITLE
audit tools incorrectly/correctly reports an audit failure ...

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/Rowan#371]
I'm running in private branch off of issue_361 (commit fd99909) where I've merge the latest alex branch (commit 5f34aa3):
```
commit 493fa68191e4dd13c700d55ac388b4a8776934b5
Merge: fd99909 5f34aa3
Author: Dale Henrichs <dale.henrichs@gemtalksystems.com>
Date:   Thu Oct 11 13:45:11 2018 -0700

    Merge branch 'alex' into audit_preview

commit fd99909e7125b56be570ace9a685324ab2b8e868
Merge: 972e45a f4d7585
Author: Dale Henrichs <dale.henrichs@gemtalksystems.com>
Date:   Wed Oct 10 17:36:39 2018 -0700

    Merge branch 'candidateV1.2' into issue_361
    
    Rowan STON Cypress Tonel FileSystemGs tests for GemStone '3.2.15'
    992 run, 977 passed, 4 failed, 11 errors
      errors
        FileHandleTest>>#testTruncate
        FileReferenceTest>>#testUpToAll
        JadeServerTest>>#test_updateFromSton
        RowanClassServiceTest>>#testAddCategory
        RowanClassServiceTest>>#testClassComment
        RowanProjectServiceTest>>#test_addPackage
        RowanProjectServiceTest>>#test_updateAddsCommandResult
        RwBrowserToolApiTest>>#testMoveGlobalExtensionSessionMethods
        RwBrowserToolApiTest>>#testNewClassVersion_session_method_unchanged_extension_method_protocol
        RwHybridBrowserToolTest>>#testHybridMoveMethodFromSessionMethodsIntoSessionMethods
        RwHybridBrowserToolTest>>#testHybridMoveMethodIntoSessionMethods
      failures
        JadeServerTest>>#test_jadeServerCanonicalLocation
        JadeServerTest>>#test_serviceUsesCanonicalJadeServer
        RwLoadingTest>>#testPoolDictionaryChanges
        RwSymbolDictionaryTest>>#testClassVersioningPatch
```
... and executed the following in a workspace:
```smalltalk
Rowan projectTools audit auditAll
```
I hit a `halt` which the removed and got the following results (bottom right corner):
![image](https://user-images.githubusercontent.com/623951/46834236-b2ca7500-cd5f-11e8-8a0c-6bf33890739c.png)
The project browser is open on the class **RwUnmanaedProjectDefinition**  and I was able to change the list of methods for which the audit is claiming "'Missing loaded method" ... the fact that the methods show up underlined and in purple impies that Jadeite thinks the **extension** methods are packaged (and therefore that the loaded method is not missing) ... **HOWEVER**, if you look closely at the method category you will see that there is a missing `*` in front the category name --- which is an audit error ... so I think the only thing wrong is that the error message is not as clear as it should be ... and **I'm glad to find this packaging error!**

**Comment by alexkogan** [comment]
#6c19f8c
Refactored audit code to be more comprehensible. Added audit on class properties such as instvars. Added printing to GsFile in RwClsAuditTool>>errorLog:add:
