### ISSUE TITLE
need simple way to run single Rowan sunit tests in topaz

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Rowan#372]
In order to debug test failures that occur only in a topaz session, it would be helpful to have a way to run a single Rowan sunit test. 

Currently, I can input this script in topaz ...
``$ROWAN_PROJECTS_HOME/Rowan/platforms/gemstone/topaz/rowanTestSuite.gs ``

... and the output conveniently summarizes errors and failures: 
```
Rowan STON Cypress Tonel tests for GemStone '3.2.17'
548 run, 534 passed, 2 failed, 12 errors
  errors
	RowanProjectServiceTest>>#test_addPackage
	RwBrowserToolApiTest>>#testMoveGlobalExtensionSessionMethods
	RwHybridBrowserToolTest>>#testHybridMoveMethodFromSessionMethodsIntoSessionMethods
	RwHybridBrowserToolTest>>#testHybridMoveMethodIntoSessionMethods
	RwRowanProjectIssuesTest>>#testIssue150_branches
	RwRowanSample2Test>>#testNoMigration_bitbucket
	RwRowanSample2Test>>#testNoMigration_gitlab
	STONLargeWriteReadTests>>#testUnicodeStrings
	STONReaderTests>>#testString
	STONWritePrettyPrinterReadTests>>#testUnicodeStrings
	STONWriteReadTests>>#testUnicodeStrings
	TonelCypressReaderTest>>#testLoadDefinitions
  failures
	RwLoadingTest>>#testPoolDictionaryChanges
	RwSymbolDictionaryTest>>#testClassVersioningPatch
```

The recommended debugging technique is to open a Jadeite session and debug the test there. However, when I ran the ``RowanProjectServiceTest>>#test_addPackage`` in Jadeite, it passed. Yet it consistently fails in topaz. 

It would be useful to have an easy way to run an individual test(s) in topaz and see both failure conditions and stack dumps.

**Comment by dalehenrich** [comment]
This is how you run individual tests in topaz when the failure only occurs in topaz:
```smalltalk
run
RowanProjectServiceTest debug: #test_addPackage
%
```
