### ISSUE TITLE
audit tools improvements

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/Rowan#374]
For issue #365, I needed to run a Rowan audit to a) identify the expected corruption in the db and b) verify that the corruption was repaired after the patch code was run ...

I was restricted from updating the Rowan code base for this patch, so I ended up [in-lining the the code from **RwClsAuditTool** and **RwClsExtensionAuditTool**](https://github.com/GemTalk/Rowan/blob/a318b6d6fae21eb41762d47e5108af6839b52d66/platforms/gemstone/topaz/3.2.15/patches/audit_issue_365.tpz) ... but in the course of testing the code, I ended up making some changes in the in-lined code that ought to be (manually) merged back into the audit tool code itself ... 

[The primary changes can be found here](https://github.com/GemTalk/Rowan/blob/a318b6d6fae21eb41762d47e5108af6839b52d66/platforms/gemstone/topaz/3.2.15/patches/audit_issue_365.tpz#L52-L94). The changes were made because it was important to identify extension methods that had been recompiled by using the standard (non-Rowan) method compilation patch, since that code path had to be used to restore the missing Globals extension methods and I wanted to make sure that I had repaired all such methods ...

**Comment by dalehenrich** [comment]
@alexkogan, there were bugs in my original script when hitting missing compiled methods. So [these patches are needed as well](https://github.com/GemTalk/Rowan/commit/f4ef3e0bcef6402060602876b52251cacc3cf0cb)

**Comment by alexkogan** [comment]
[adopted said changes](https://github.com/GemTalk/Rowan/commit/b271b563bd2a3e49c2101d43fe3f1e64c5ff3749)

**Comment by dalehenrich** [comment]
With this commit bcad17a, the audit tool is tergeted to be included in the candidateV1.2 branch and Issue #393 bugfix
