### ISSUE TITLE
Definition-based project creation does not put packages in config file

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Rowan#379]
When I create a project using definitions, it creates the spec and config file and writes out the packages and methods.  However, it does not update the configuration file with the package names, and therefore, a subsequent load will succeed but will not actually load the actual classes. 

It's not at all obvious how you would update the configuration file programmatically...

**Comment by dalehenrich** [comment]
With the current V2.0.0 work,  added packages are added to the configurations/components data structures ... the configurations are written when the packages are written as well
