### ISSUE TITLE
Should package by name lookup be case insensitive?

### ISSUE THREAD

**Issue by alexkogan** [GemTalk/Rowan#400]
RwGsImage class>>loadedPackageNamed: currently looks up packages by they keys making it case sensitive naturally. 
Rowan image loadedPackageNamed: 'Audit-Extensions' finds package with corresponding name.
Jadeite (rowan api) permits creating extension categories with any letter case hence 
Rowan image loadedPackageNamed: 'audit-extensions' will fail though it is perfectly legitimate category/package name

**Comment by dalehenrich** [comment]
method category names like `*audit-extensions` or `*AuDiT-eXtEnSiOnS` are a carry over from Monticello where the category names were case-insensitive. Rowan needs to support this Monticello convention, thus the *case insensitive* ... when Jadeite is ready to start supporting non-Monticello convention, then the name of the method category will no longer matter and will only be used with Packages/Projects that are using the Monticello convention --- something that will likely exist a long time ...

Package names are case sensitive.
