### ISSUE TITLE
code missmatch between topaz and jadeite

### ISSUE THREAD

**Issue by alexkogan** [GemTalk/Rowan#419]
I've updated method in audit code using Jadeite after seeing some artifacts from running audit in topaz. Commited. 

topaz doesn't pick up updated method even after logout. In actual execution Jadeite runs new version topaz runs old version.
![topaz](https://user-images.githubusercontent.com/1958382/48663202-85997280-ea41-11e8-93f4-e84e5e9044b4.jpg)
![jadietemethod](https://user-images.githubusercontent.com/1958382/48663204-892cf980-ea41-11e8-83f1-969660ecd043.jpg)

**Comment by dalehenrich** [comment]
GemStone commits work, the fact that logout/login implies that the commit didn't commit ... what happens if you logout/login in Jadeite ... 

I'm suspicious that perhaps there was a commit conflict and the Jadeite commit silently failed, perhaps?

**Comment by alexkogan** [comment]
Logged out of Jadeite as well.

**Comment by dalehenrich** [comment]
... and what happens when you logout/login of Jadeite?

**Comment by alexkogan** [comment]
They are different still

**Comment by dalehenrich** [comment]
Well that can really only mean that you aren't sharing the same class version or not logging in as same user/stone/symbolList as is used by Jadeite ... don't you agree? 

GemStone does not provide different environments to the same user on the same stone depending upon whether they use topaz or gci, right? ... there has got to be some logical explanation ...

**Comment by alexkogan** [comment]
10543

Oscar 3.0.45

**Comment by dalehenrich** [comment]
Some observations after logging in:
1. the code loaded in the stone is from v1.1.0 (09e68a0)
2. your Rowan repo is much newer: `f0aa818 26 hours ago some more adjustments to audit`
3. the audit classes have not been loaded using Rowan ... they are not visible in the project browserbut you can see them in the Dictionary browser ... 
   ![image](https://user-images.githubusercontent.com/623951/48676150-69680500-eb17-11e8-94d8-d32cb48860c0.png)

I cannot log into your stone ... so I can't check anything else out:
```
rogue:rowan_dev_3215>topaz -i
 _____________________________________________________________________________
|             GemStone/S64 Object-Oriented Data Management System             |
|                   Copyright (C) GemTalk Systems 1986-2016                   |
|                            All rights reserved.                             |
+-----------------------------------------------------------------------------+
|    PROGRAM: topaz, Linear GemStone Interface (Remote Session)               |
|    VERSION: 3.2.15, Fri May 13 10:35:30 2016                                |
|      BUILD: gss64_3_2_x_branch-39522                                        |
|  BUILT FOR: x86-64 (Linux)                                                  |
|       MODE: 64 bit                                                          |
| RUNNING ON: 8-CPU rogue x86_64 (Linux 4.15.0-38-generic #41~16.04.1-Ubuntu  |
| SMP Wed Oct 10 20:16:04 UTC 2018) 32062MB                                   |
| PROCESS ID: 16000     DATE: 11/18/2018 10:05:31 PST                         |
|   USER IDS: REAL=dhenrich (562) EFFECTIVE=dhenrich (562)                    |
+-----------------------------------------------------------------------------+
|   GEMSTONE_NRS_ALL = #dir:$GEMSTONE_LOGDIR#log:%N%P.log                     |
|_____________________________________________________________________________|
topaz> input malta.topazini
topaz> set gemnetid !tcp@malta#netldi:10543#task!gemnetobject
topaz> set gemstone akogan64bit32x
topaz> set u SystemUser p swordfish
topaz> login
[Info]: libssl-3.2.15-64.so: loaded
-----------------------------------------------------
GemStone: Error         Fatal
Unable to create a GemStone session, check netldi log file.

Error Category: [GemStone] Number: 4042  Arg Count: 0

Login failed due to errors.
topaz> status

Current settings are:
 display level: 0
 byte limit: 0 lev1bytes: 0
 omit bytes
 display instance variable names
 omit oops
 oop limit: 0
 omit automatic result checks
 omit interactive pause on errors
 listwindow: 20
 stackpad: 45
 tab (ctl-H) equals 8 spaces when listing method source
 using line editor
   line editor history: 100
   topaz input is from a tty on stdin
EditorName________ 

CompilationEnv____ 0
Connection Information:
UserName___________ 'SystemUser'
Password __________ (set)
HostUserName_______ ''
HostPassword_______ (not set)
NRSdefaults________ '#dir:$GEMSTONE_LOGDIR#log:%N%P.log'
GemStone___________ 'akogan64bit32x'
GemStone NRS_______ '!#dir:/home/dhenrich/rogue/_homes/rogue/_home/server/stones/rowan_dev_3215/logs#log:%N%P.log#server!akogan64bit32x'
GemNetId___________ '!tcp@malta#netldi:10543#task!gemnetobject'
GemNetId NRS_______ '!@malta#netldi:10543#dir:/home/dhenrich/rogue/_homes/rogue/_home/server/stones/rowan_dev_3215/logs#log:%N%P.log!gemnetobject'
CacheName___________ (default)

SourceStringClass    String
fileformat           8bit
```
I assume that I've messed up the NRS, but search me for figuring out what the NRS should be ... or even if that is the real problem..

**Comment by dalehenrich** [comment]
... need to add a call to `Behavior>>_codeChangedForEnv:` when installing a method directly in the method dictionary

**Comment by dalehenrich** [comment]
Actually `Behavior>>_clearLookupCaches:` appears to be needed for the current session and `Behavior>>_codeChangedForEnv:` is needed to notify other sessions of the need to clear send site caches

**Comment by dalehenrich** [comment]
@alexkogan has confirmed that the patch addresses the behavior he was seeing ....
