### ISSUE TITLE
Need `existsOnDisk` message for RwProject ...

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/Rowan#428]
... to answer whether or not the project has been written to disk or exists only in memory ...

**Comment by dalehenrich** [comment]
at the moment I don't think it is possible to have a loaded project that does not exist on disk, but for v2.0.0 I may be headed that direction ...

**Comment by dalehenrich** [comment]
Turns out that the following expression will produce a loaded project that has not been written to disk ... so tests can be written ...

**Comment by dalehenrich** [comment]
... time for tests

**Comment by dalehenrich** [comment]
passing tests are present ...

**Comment by ericwinger** [comment]
@dalehenrich Would you expect a project created with the sample code (https://github.com/GemTalk/Rowan/issues/428#issuecomment-441870287) to show as skew in the browsers?  

Seems like the fact that it's not on disk should warrant a "skew" display, but I don't know the definition of skew well enough to say that for certain.

**Comment by dalehenrich** [comment]
No I would not ... skew is intended to indicate that the SHA at the time the code was loaded from disk does not match the current SHA of the repository on disk ... if the project is not present on disk, then there cannot be skew --- the fact that it is not present on disk, could be indicated by simply showing the project as dirty -- which means that the in image source does not match the disk source ... which would be true:) ... I'm somewhat inclined to wait until we start working on v2.0.0 to fine tune the project info display ... in v2.0.0 I'm changing how projects are created/cloned/etc. so some of the needs will change along with the implementations...

**Comment by ericwinger** [comment]
Ok, I'll leave the display alone but fix the test to show that without a project on disk there is no skew. Thanks.

**Comment by ericwinger** [comment]
Err, rather I'll change ``isSkew`` in services to return ``false`` if the project is not on disk.
