### ISSUE TITLE
`rename` package would be useful

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/Rowan#466]
do all the right things: rename class categories and method protocol if needed; delete the old package on disk... pretty tedious if done manually

**Comment by regkrock** [comment]
Does this mean the entire refactoring browser capabilities. I have spent so much time changing method names, class names, etc. It is frustrating. I miss the class rename feature in tODE! Without these tools we are in the dark ages of the early 90's.

Companies do not want to pay for low value work. The renaming is low value work. All of the things accomplished by the refactoring browser capabilities replaces low value work.

**Comment by dalehenrich** [comment]
rename package method added to RwResolvedProjectV2 in commit d57c31fc and Issue #590 will finish the job
