### ISSUE TITLE
`rename` class would be useful

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/Rowan#470]
do all the right things ... create new class, copy methods over, make subclasses of old class subclasses of new class ... optionally make the new class a member of the old classes classes class history ...

**Comment by dalehenrich** [comment]
At this point, `Rowan projectTools browser renameClassNamed: 'oldClassName' to: 'newClassName.` is functional ... the only real missing component would be refactoring browser functionality that edits methods and swaps out method references to the old class with a reference to new class ... this can be done manually by a developer after the rename is complete (assuming that they have collected references to the old class before doing rename) ...

**Comment by dalehenrich** [comment]
Ready for integration into Jadeite ... when it makes sense (GemTalk/Jadeite#439)

**Comment by ericwinger** [comment]
Jadeite should support rename class now. https://github.com/GemTalk/Jadeite/issues/439
