### ISSUE TITLE
Jadeite - Inspector on characters in iso88599 fails

### ISSUE THREAD

**Issue by regkrock** [GemTalk/Rowan#473]
I inspected the following code in Jadeite workspace:

     (ZnCharacterEncoder newForEncoding: 'iso88599') characterDomain

An inspector was opened but when I attempted to drill into the 'dict' instance variable by double clicking on it, an error occurred. The error is shown below:

![image](https://user-images.githubusercontent.com/7550442/53422641-dd833600-39ad-11e9-8fd3-0d03c58d6ff2.png)

**Comment by ericwinger** [comment]
@dalehenrich @regkrock ZnCharacterEncoder doesn't exist in my image. Do you have a reproduction case using a base image class?

**Comment by LisaAlmarode** [comment]
Inspect: (Set with: (Character withValue: 353))
then double click on "dict".

**Comment by LisaAlmarode** [comment]
Closing this since the Jadeite issue is where it will get attention.  Hopefully.
