### ISSUE TITLE
rename class with class reference in same hierarchy gives compiler error

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Rowan#502]
Per the comment below from https://github.com/GemTalk/Rowan/issues/470#issuecomment-463365292, rename class shouldn't error if the class is referenced in the hierarchy. Jadeite will handle the error better in https://github.com/GemTalk/Jadeite/issues/499. Creating a new bug so the issue can be referenced separately. 

> Currently if a method in one of the subclasses of the old class reference the old class by name, a compile error will occur...

**Comment by dalehenrich** [comment]
FWIW, this is a "known" limitation of the current rename algorithm ... to do the job right we need to get into the refactoring browser business ... also don't plan to address this issue for v1.2 ... currently rename is caveat emptor...

**Comment by dalehenrich** [comment]
With the current technology, I think that bringing up the dialog with the compile error is the right aswer ... so closing
