### ISSUE TITLE
Collect all failed method recompiles after class compilation

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Rowan#503]
Currently, Jadeite sends ``_compileInContext:symbolList:`` to a definition string to recompile a class. If successful, it returns an anonymous method which recompiles the methods in the class. The two-step compile is nice because class compile errors can be separated from the method compile errors. 

It would be nice if the anonymous method would collect all method compile errors before reporting the results. Currently, if any method fails to recompile, a ``CompileError`` is raised which Jadeite can handle. It would be nicer if Jadeite could report all compile errors at once. 

One possibility is to create a rowan variant of  ``_compileInContext:symbolList:`` to do this.

**Comment by dalehenrich** [comment]
GemTalk/Jadeite#390 seems to have filled the bill ...
