### ISSUE TITLE
Unloading large project gets temp obj memory full error

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Rowan#529]
I created a large project using the script in #384. The script was modified to set the superclass to ``TestCase`` and the method count per class was 25.  On unload I get the memory error below. 

No Jadeite windows were open except the console (hence no other updates). To unload I used the console unload menu option. Temp obj configuration settings should be default. 

![image](https://user-images.githubusercontent.com/36212516/68794360-b932bc80-0603-11ea-9283-407b45497596.png)

**Comment by dalehenrich** [comment]
To do the unload, increase the size of your TOC ... I'm not inclined to do anything about TOC issues at the present time ... once v2.0 is fully functional it will be time to evaluate memory footprints, etc.
