### ISSUE TITLE
Compiling a class method creates an instance method

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Rowan#547]
If you create or update a class method that is not rowanized, it works but both cases create instance methods.

The following:
AbstractCharacter  rwCompileMethod: 'badger' category: 'other'
AbstractCharacter class rwCompileMethod: 'stoat' category: 'other'

raise an error but if you continue, they both create instance methods.
It's reproducible without the error walkback directly from Jadeite - see https://github.com/GemTalk/Jadeite/issues/625

**Comment by dalehenrich** [comment]
fix on latest `candidateV1.2` branch
