### ISSUE TITLE
[V2.0] Add package needs default componentName for older client tests

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Rowan#623]
In Rowan services, `RowanProjectService>>addPackageNamed:` needed to be removed and `addPackageNamed:toComponentNamed:` was added.  However, the Jadeite client relies on the removed method, `addPackageNamed:`. 

Obviously, Jadeite is going to support the new api, client tests still need to pass until that is fully supported. @dalehenrich said that Core can be used as a default. Opening Rowan ticket for tracking and will open & reference a Jadeite ticket that adds a temporary work around for Jadeite tests which restores `addPackageNamed:`

**Comment by ericwinger** [comment]
> I have been using `Core` as the "default" component name, but I'm reluctant to define a default ... in the V2.0 Jadeite, I'm expecting that the component will be represented in the browser, so there will be selected component available and the package would be added to the selected project and component .without needing to specify a default ... I think a Rowan issue necessary ... given that the GUI will be responsible for making sure that the user chooses which compoent to add the package to ...
<sub>[View in Slack](https://gemtalksystems.slack.com/archives/DTQTTMC07/p1592416215358400)</sub>

**Comment by dalehenrich** [comment]
I'm not sure this is a Rowan bug ... The V2.0 api is what it is and having a default component name is short term hack that should be used in tests only (the add package function needs to be disabled in Jadeite (and was effectivel disabled by removin `RowanProjectService>>addPackageNamed:` and that should remain disabled, until the Jadeite is able to use the current V2.0 api....
