### ISSUE TITLE
package does not get dirtied after rwMoveMethod:toCategory send

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Rowan#640]
For some reason, this code does not dirty the package. See https://github.com/GemTalk/Jadeite/issues/838

I would have thought it should. 

```
(RwPackage newNamed: 'Filein4Rowan') isDirty <false>
CharacterCollection rwMoveMethod: #subStrings: toCategory: '*filesystem-gemstone-kernel'.
(RwPackage newNamed: 'Filein4Rowan') isDirty <false>
```

**Comment by dalehenrich** [comment]
in my image (latest candidate) the method subStrings: is in the package Filein1A and when I execute that expression I get dirty packages ... so you are looking in the wrong place, probably ...

**Comment by ericwinger** [comment]
Yes, I see and I think I see the problem in Jadeite. Retiring.
