### ISSUE TITLE
Need method to return a component's display name

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Rowan#654]
Related to https://github.com/GemTalk/Rowan/issues/653

When displaying components in the Jadeite project browser, a convenience method is needed to return the logical name of the component.  Example: 
```
self: aRwSimpleNestedProjectLoadComponentV2 common/AST for project Rowan
-.asOop: 274255617
-name: 'common/AST'
-comment: ''
-projectName: 'Rowan'
-conditionalPackageMapSpecs: aDictionary( )
-preloadDoitName: nil
-postloadDoitName: nil
-doitDict: aDictionary( )
-packageNames: anArray( )
-condition: 'common'
-componentNames: anArray( 'common/platforms/AST')
-projectNames: anArray( )
```

The name is `common/AST` but that isn't a good name to display in a browser because it contains meta data about the directory structure. Instead, `AST` should be displayed. 
Suggested names:  `displayName` or `shortName`

**Comment by dalehenrich** [comment]
I'm inclined to go with `basename` ... this is the selector used by FileSystem for getting the terminal name in a path ... also basename is the name of the bash function ...
