### ISSUE TITLE
Only display some subcomponents

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Rowan#655]
Related to https://github.com/GemTalk/Rowan/issues/653

When displaying subcomponents in the Jadeite browser, it is not necessary, nor proper, to display all the levels of subcomponents. One should be able to ask the component (`aRwSimpleNestedProjectLoadComponentV2`) to return "visible" subcomponents. Perhaps a method named `visableSubcomponentsOf:` in `RwProject`? 

One **possible** implementation is to have an attribute on a component which indicates if it is hidden or not.  Default is to be displayable (hidden=no) if the attribute is not present. `visibleSubomponentsOf:` would return those components with attribute hidden=no.

**Comment by dalehenrich** [comment]
at the moment I'm inclined to implement `visibleSubcomponentNames:` as a list of names that is a subset of componentNames ... at least in the short term ... when we get further into the gui design I'm anticipating that we will do a final refactoring of the classes as well as creating `loaded` component classes which could easily have completely different classes and structure that the current set of classes that are being used to specify the structure ...

**Comment by dalehenrich** [comment]
implemented RwProject>>loadedSubcomponentsOf:, RwProject>>loadedSubcomponentsOf:attributes:ifNone:, RwProject>>loadedSubcomponentsOf:ifNone: and I think that tehse methods fill the bill. Each of these methods returns the direct sub components of the given component and each of the components is guaranteed to be `loaded` which I think is equivalent to visible ... RwProject>>allClassNamesFor: and RwProject>>allPackageNamesIn: provide the full list of class names or package names `visible` in the all of the subcomponents for the list of named  compoents.
