### ISSUE TITLE
Make sure there's a way for Rowan to add methods and classes "outside Rowan"

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Rowan#72]
What happens if you try to compile a method for a class that is not in a rowan package and does not have a *'d category?

**Comment by dalehenrich** [comment]
from issue #70, add, update and delete need to be supported

**Comment by dalehenrich** [comment]
At the moment, **RwPerformingUnpackagedEditNotification** throws an error by default , but if you look at the tests, you can see that there are multiple options for handling the exception:
https://github.com/dalehenrich/Rowan/blob/cb493423f3810826d6841d72828d1e7ad9cebdb5/src/tonel/Rowan-Tests/RwRowanProjectIssuesTest.class.st#L8-L218
Not to mention the fact that we could easily arrange for a different default action to be used by **RwPerformingUnpackagedEditNotification** ...

Bouncing to @ericwinger for final tweaks

**Comment by ericwinger** [comment]
Jadeite needs to handle Rowan confirms. Once that happens, we can change the error to a confirm. Deferring to post alpha.

**Comment by dalehenrich** [comment]
With the completion of #364, this issue will be addressed
