### ISSUE TITLE
Clean up file url parsing in Rowan ...

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/Rowan#733]
Slack question from Andrei Chiș:
```
Quick question. Not sure if it is a feature or bug :slightly_smiling_face:. When specifying projectFromUrl: we were using before file://$ROWAN_PROJECTS_HOME  and if I remember correctly it was working in 3.7.0-alpha one.  Now we changed it to file:$ROWAN_PROJECTS_HOME  and all works as expected. Is file://  also expected to work? I though that's the way to indicate an absolute path.
```
My response was:
```
Regarding file:// , I will have to say that I haven't looked at the specs (yet), but according to wikipedia[1] it seems that both are correct and with my quick scan, there doesn't seem to be a (legal?) way to define a relative path with a file url :slightly_smiling_face:. I do remember that when I went about supporting environment variables in the file url, that I had to tweak some things ... file:/path is a legal file url for the local host, but I seem to remember that the url parser croaked when I fed it file:$ROWAN_PROJECTS_HOME and at the time, I "wanted that to work" in retrospect, I think that I should have used file://$ROWAN_PROJECTS_HOME  (which should have worked) ... 
[1] https://en.wikipedia.org/wiki/File_URI_scheme
```
but I'm not happy with the answer ... I need to read the spec and write some more tests to make sure we conform to the spec ... I also need to take a look at the current Pharo implementation and see how they handle things ... 

my interpretation is that file urls don't support relative paths, but if Pharo does, I need to decide how to go ... IIRC, the code checked if the first character was $/ and create an absolute path and using an environment variable threw a monkey wrench into that scheme ... if push comes to shove I'm inclined to have environment variables win ...

GemStone does not really have the notion of a "working directory". The environment variable PWD (in the context of a gem) resolves to the directory in which the netldi is started, but that directory is not always accessible/writable by the user running a topaz session ... Gems may or may not be running on the same host as the stone or even the same host as the user that invoked the gem.

Relative paths are currently "supported", but the following smalltalk expression and printString of the result  shows the ambiguity:
```
{
	'file://$ROWAN_PROJECTS_HOME' asRwUrl pathString asFileReference asAbsolute.
	'file:$ROWAN_PROJECTS_HOME' asRwUrl pathString asFileReference asAbsolute.
	'file:abc' asRwUrl pathString asFileReference asAbsolute.
	'$PWD' asFileReference .
	'file:$ROWAN_PROJECTS_HOME' asRwUrl isAbsolute.
	'file:abc' asRwUrl isAbsolute.
	'$PWD' asFileReference isAbsolute.
}
  anArray( 
	File @ /, 
	File @ /home/dhenrich/rogue/_homes/rogue/_home/shared/repos, 
	File @ /home/dhenrich/rogue/_homes/rogue/_home/server/stones/feenk_370_alpha2/logs/abc, 
	File @ /home/dhenrich/rogue/_homes/rogue/_home/server/stones/feenk_370_alpha2/logs, 
	false, 
	false,
	true)
```
**note that the first item (file://$ROWAN_PROJECTS_HOME) is not parsed correctly.**

At the end of the day, we really have to have a definitive answer for what is a "working directory" and unfortunately the answer really depends upon whether the gem is running on the same host as the stone or even the same host as the user that invoked the gem ... there are scenarios where the gem cannot read files on the end user's machine and the end user may not know where the "working directory" is located without asking ... so overall we might be better off not supporting relative paths in file urls and avoid any confusion that may exist ... 

With all of that said, I would like to hear additional suggestions for the definition of the working directory for a GemStone gem, given these three scenarios:
1. user, gem and stone are on same machine
2. user and gem on same machine, stone on different machine
3. user, gem and stone are all on different machines ..

I think the stone machine can be ignored, but at this point i will still include it ...

As a secondary issue we should discuss how/when environment variables can be resolved (can/should an environment variable be a relative path) ...

**Comment by akgrant43** [comment]
Hi Dale,

Given that multi-machine & multi-user nature of the GemStone server, I agree that the concept of a working directory is difficult to maintain.  

If anything, my first thoughts are:

- working directory = $GEMSTONE.
- all servers that are part of the GemStone server are required to have the same directory structure below $GEMSTONE

I haven't looked at all at running GemStone on multiple machines, so the second point may not make sense, but it would be consistent at least from the perspective of accessing it as a working directory.

**Comment by dalehenrich** [comment]
@akgrant43, interesting thought ... $GEMSTONE happens to be a reference to the product tree and is mostly read only (to protect the integrity of the product bits), another thing about $GEMSTONE is that it can be shared by multiple stones, so there may not be a single, well-known directory in which to stash user/stone/application data... 

But you are putting your finger on one of the associated problems (in my opinion): We do not promote/support/require a standard installation structure for a stone. As an aside, there are ways to discover the location of a number of important locations from within a gem. There are a number of "well known locations" in GemStone (identified by an environment variable or a method call):
- gem log directory
- extent location
- tranlog directories

Our apis are more aimed at making it possible for customers to heavily customize their GemStone installation than providing/dictating structure. There are good reasons for this as a customer is free to lay out their stone installation directory structure as they see fit: putting extents and tranlogs on multiple "disk drives" and putting their log files where they need/want, however it means that new users have to make their own decisions as to where to put things.

At the end of the day, I'm not sure that we can define the location of a single working directory and it seems that trying to support a relative file url can never work, 

Hmmm, if we allowed user's to define their own working directory then relative files can be used, but given the fact that gems can be running on multiple machines the definition would have to be a block that executed code to calculate the location?

It just seems simpler overall to disallow relative paths in file urls and users can use environment variables or a message sends or a whatever to provide their own notion of a working directory in the context of their application to construct an absolute path.

In GsDevKit_home, I **do** provide well known locations for everything and in tODE, there is a workingDirectory defined ($PWD of directory where netldi was started), but in practice I never relied on the working directory mainly because I had defined env variables for all of the important GsDevKit_home locations and the scripts that I wrote were more portable understandable if I used the env var ... which was better than to try to create relative paths against a single directory ...

I'm not giving up on the concept of a "working directory" for GemStone yet ... 

@akgrant43 and @chisandrei, it would help me if you gave me some concrete examples of what you use relative paths for in your everyday development? Also I'm curious if you work in a single image all of the time, or do you regularly hop from image to image ...

I have ~70 stones defined and right now I have 6 stones currently running and it represents two working sets of stones  for two different projects that I'm working on at the moment ... I have a single central directory of git repositories that are shared by the 70 stones ... each stone has a local git repository that is used off and on when the git repository I'm working with should not be shared (I'm using the stone local git repositories in one of my current projects) ... I store all of my working shell scripts and "temp files" in the stone directory, but the shell scripts tend to run scripts using absolute paths encoded in environment variables that are defined "in" the netldi (for gci gems) and local topaz sessions ... the set of env vars and scripts is dependent upon the project that I'm working on ... a lot of my work involves multiple stones (typically multiple  gemstone versions) per project   ... 

Sooooo, I am biased towards using env vars and sharing scripts with multiple stones and using this model for over ten years (I am BIASED :) ) ... 

So I do need to hear about how you structure your development in an environment where relative paths are part of the working environment so I can better understand that model and then map it to GemStone ...

**Comment by akgrant43** [comment]
Hi Dale,

Going back to basics a little, the 'working directory' is the default location against which relative paths are resolved.  Rather than trying to specify a working directory that makes sense in all configurations, it may make more sense to allow the working directory to be specified programmatically.  That way customers that want a default location for resolving relative paths can specify it on a case-by-case basis, and everyone else can ignore it.

Just in case the importance of relative paths is being overestimated...  The initial issue for us was that environment variables weren't being substituted correctly when we used a URL of the form `file://$ENV_VAR', we had to use `file:$ENV_VAR`.  This was working in Alpha 1, and stopped in Alpha 2.  ENV_VAR is always absolute in our case, so the issue was just about getting it working.  Andrei's comment about it being absolute was more of an aside, than the root issue.

Just to answer your question about my use of relative paths...  I typically have two images in use: one which is my current development image, and which typically gets rebuilt from scratch between every 1 and 7 days to pick up changes from the rest of the development team; and a second image, which is just a slightly older version of my development image, which gets used for the command line utilities that I have (automatically archiving files, running backups, etc.).  Using a slightly older image simply means that it isn't being changed, doesn't have the changes file open, etc.  (I do have an even older image on the home server, which checks disk space, deletes security video from ZoneMinder (keeps the disk 80% full), etc., and is only rebuilt when something changes).

The relative paths are important for the second case, running CLI utilities, where the files are specified on the command line and are relative to the working directory.

If these were using GemStone, or any other back-end server, I'd expect the client to take care of mapping the relative paths to something that the server understands.  So the working directory would be a client-side concept.

**Comment by dalehenrich** [comment]
@akgrant43, thanks for clarifying the actual issue as I missed that detail in the earlier discussions ... I've opened Issue #737 to address that specific bug in Rowan.

With regards to introducing an API for setting working directory, @kurtkilpela has submitted  GemTalk/FileSystemGs#43 to implement your suggestion.  As an FYI, GemTalk/GemTalk/FileSystemGs is a rewrite of the FileSystemGs implementation currently present in Rowan ...while it is getting close, it isn't quite ready for production ...

Thanks for spending the time discussing this ... this bug has served it's purpose :)
