### ISSUE TITLE
project audit output regression in v3.0

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Rowan#745]
In Rowan v3.0, doing
```
(Rowan projectNamed: 'Rowan') audit
```
gives this output
```
 aKeyValueDictionary( )
```
which isn't very helpful. Prior versions of Rowan gave output something like this: 
```
Auditing project Rowan
Audit Report for project Rowan
...
```

**Comment by dalehenrich** [comment]
provide programmatic access to audit log ...
