### ISSUE TITLE
Loaded project no longer understands #symbolDictNameForPackageNamed:

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Rowan#746]
Adding a method category with an * required a check that the extension package exists in the same dictionary as the loaded project. However, the loaded project no longer understands #symbolDictNameForPackageNamed: in Rowan V3.0. 

![image](https://user-images.githubusercontent.com/36212516/131408421-1e33008c-9e9d-4e2a-bb28-964dda1edd6c.png)

**Comment by dalehenrich** [comment]
This was a case where the method was renamed to RwProject>>gemstoneSymbolDictNameForPackageNamed: ... so it was intentional ...
