### ISSUE TITLE
Removing loaded project fails to find project in project registry

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Rowan#748]
This looks like a bug although there could be a different api required in v3.0.  If I find a project with `Rowan image loadedProjectNamed:ifAbsent:` I would think the project would be found in the project registry and thus removable. 

If it is a bug, perhaps it's related to recently fixed bug https://github.com/GemTalk/Rowan/issues/740?

Attaching a stack, too. 

![image](https://user-images.githubusercontent.com/36212516/131414065-6e7ac21f-cbf0-4c12-a24d-d7a5a782f4fa.png)

[20210830_remove_loaded_project_cannot_be_found_stack.txt](https://github.com/GemTalk/Rowan/files/7079919/20210830_remove_loaded_project_cannot_be_found_stack.txt)

**Comment by dalehenrich** [comment]
Hmmm, this is a new one ... the pattern in your test is a pretty common one used  in a bunch of the tests ... so there is definitely something fishy here ... I might have to put my hands on the image to fix it ...

**Comment by ericwinger** [comment]
Login info sent in slack.

**Comment by dalehenrich** [comment]
This one appears to be related to project tests and there are a couple of relatively illegal things that have been done in managing test projects that can lead to this kind of error ... should not be possible in normal operation
