### ISSUE TITLE
Send of #_signalWith:

### ISSUE THREAD

**Issue by martinmcclure** [GemTalk/Rowan#771]
In ``masterV2.2``, ``RwAllowChangeRepositoryRevisionOnResolveNotification>>signal:`` sends ``_signalWith:``, which has been removed from GemStone 3.7.

This results in a failure in fastRowan when using a non-default branch of RowanClientServices.

It looks like a send of ``signal`` should do just as well. I'll make that change and test by re-doing the build that failed.

**Comment by martinmcclure** [comment]
A default 3.7 build is unable to load Sparkle due to this bug; reopening until the fix can be merged to the branch 3.7 is using by default.

**Comment by dalehenrich** [comment]
I just pushed a new version of candidateV2.2 which is the heir apparent to masterV2.2 ... waiting for 3.6.3 to finish it machinations before merging into masterV2.2 ... so if you switch to candidateV2.2 in externals_st.config.default:
```
@externals_st =
  (
   [ "true", "Rowan", "Rowan", "candidateV2.2", [11, 51] ],
   [ "true", "RowanClientServices", "RowanClientServices", "masterV2.2", [11, 51] ],
   [ "true", "GsDevKit_upgrade", "GsDevKit_upgrade", "master", [11, 51] ]
  );
```
Things should work for you ... I just did a successful build before lunch ... let me know if there are any additional problems ...

**Comment by dalehenrich** [comment]
I believe that this is fixed now ...

**Comment by martinmcclure** [comment]
Yes, looks like that fix did get merged to masterV2.2.
