### ISSUE TITLE
v3.0 need set of subcomponentsOf: messages in RwAbstractUnloadedProject that parallel loadedSubcomponentsOf: in RwProject

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/Rowan#780]
@ericwinger needs these for working with defined projects in Jadeite ... deliver this feature along with new stone ...

**Comment by ericwinger** [comment]
Ideally, these accessors would make it easy to build a hierarchy of components and subcomponents for a project.

**Comment by dalehenrich** [comment]
... if you need something different from the load* variants, let me know what you need to "make t easy"

**Comment by ericwinger** [comment]
That should work.

**Comment by dalehenrich** [comment]
looks like things are in good enough shape for @ericwinger to take things for a spin
