### ISSUE TITLE
Package Groups persisted beyond the life of the definition

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Rowan#789]
If I make changes to a package group inside of a newly-instantiated project definition on loaded Project A, those changes will show up in every new project definition created from loaded Project A. However, changes to a package group should not live beyond the life of the project definition unless the definition has been exported to disk. 

This could lead to someone thinking they've made a change to their package group but, in fact, it's not written to disk at all.

**Comment by dalehenrich** [comment]
The key information here is that the the project definition is created from a loaded project and when the project definition is dropped on the floor, the package group modifications appear to be made to the loaded project ... looks like a missing copy when creating project definition from loaded project?

**Comment by dalehenrich** [comment]
Tried to reproduce the bug and neither @ericwinger nor I am able to reproduce ... in fact the code that I wrote to `make changes to a package group` ends up adding a package groupd in the wrong place.
Load RowanSample9:spec_0061:
```
| fileUrl spec loadSpec resolvedProject |
	fileUrl := 'file:$GS_HOME/shared/repos/Rowan/test/specs/RowanSample9_0000.ston'.
	spec := (RwSpecification fromUrl: fileUrl)
		projectsHome:  '/home/dhenrich/rogue/_homes/rogue/_home/server/stones/rowan_dev_l/git/testRepositories';
		yourself.
	spec revision: 'spec_0061'.
	resolvedProject := spec resolveStrict.
"load project"
	resolvedProject load.
```
then code to `make changes to a package group inside of a newly-instantiated project definition` and then `show up in every new project definition created from loaded Project A`:
```
| groupNames loadedProject definedProject |
loadedProject := (Rowan projectNamed: 'RowanSample9').
groupNames := loadedProject packageGroupNames.
definedProject := loadedProject defined.
definedProject halt addPackageGroupNamed: 'groups/XXX' condition: 'common' comment: 'hello'.
{ 
	definedProject packageGroupNames . 
	groupNames . 
	loadedProject packageGroupNames .  
	loadedProject defined packageGroupNames
 }
```
`groupsXXX` shows up in the wrong place altogether (see #822)

**Comment by ericwinger** [comment]
That was not correct code to reproduce the problem. This is (at least) one reproduction case.  The change to the package group should not show up in the other definition because the change wasn't first written to disk. 

```
| groupNames loadedProject definedProject packageGroup definedProject2 packageGroup2 |
loadedProject := (Rowan projectNamed: 'RowanSample9').
groupNames := loadedProject packageGroupNames.
definedProject := loadedProject defined.
packageGroup := definedProject packageGroupNamed: 'groups/Rowan'. 
packageGroup comment: 'adding a new comment'. 

definedProject2 := loadedProject defined. 
packageGroup2 := definedProject2 packageGroupNamed: 'groups/Rowan'. 
packageGroup2 comment ===>  'adding a new comment'
```

**Comment by dalehenrich** [comment]
it turns out that we are not copying the packageGroups during `asDefinition`:
```
	definedProject1 := loadedProject defined.
	packageGroup1 := definedProject1 packageGroupNamed: 'groups/Rowan'.

	definedProject2 := loadedProject defined.
	packageGroup2 := definedProject1 packageGroupNamed: 'groups/Rowan'.

"validate"
	self assert: definedProject1 ~~ definedProject2.
	self assert: packageGroup1 ~~ packageGroup2. "<---- assertion fails"
```
so we need to make sure that all of the components of a loaded project are COPIED in the process of creating the defined project ...

**Comment by dalehenrich** [comment]
turns out that packageGroup and conditionalPackageMapSpecs are not being copied correctly ... need to have test coverage for the different component hierarchies
