### ISSUE TITLE
sending `read` to RwDefinedFromResolvedProject doesn't seem to pickup disk changes

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Rowan#794]
I executed this code but did not seem to get the disk changes into the instantiated definition. 
```
(Rowan projectNamed: 'RowanSample9') defined read
```
In my image, sending `defined` to the project returns a RwDefinedFromResolvedProject which I then send `read` to. But it seems that the disk changes to the load spec's comment aren't in the instantiated loadSpec in the definition. 

Here's the instantiated loadSpec comment:
![image](https://user-images.githubusercontent.com/36212516/152439403-84feb60c-cf87-4529-bba9-83eaf4d45e44.png)

Here's what's on disk.  Note the difference in the comment on disk that's not shown in the image:
![image](https://user-images.githubusercontent.com/36212516/152440948-4bac1b40-0b3d-4fe0-bbbc-bbecb8a1f7d2.png)

**Comment by ericwinger** [comment]
Perhaps my assumption that the load spec will also be picked up from disk was not correct?

**Comment by dalehenrich** [comment]
load specs are not read from disk on a #read ... as I've mentioned before, the load spec is a special guy ...  the edits you make to the load spec are used to actually read the rest of the project from disk, so you have to be explicit about saving changes to load specs and if you want to read a load spec you have to explicitly read it from disk ...

**Comment by dalehenrich** [comment]
I think we can call this one fixed?
