### ISSUE TITLE
Renaming component then moving package to renamed component gives walkback

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Rowan#807]
If I rename a component, say `common/tests/Tests` in RowanSample9 to `common/tests/Tests/fnoodle` then move a package into the renamed component, I get this walkback
```
The component 'common/tests/Tests/fnoodle' is undefined
```
The two rowan project definition api's in play are: 
1. renameComponentNamed:to:
2. movePackageNamed:toComponentNamed:

I verified that the RowanSample9 project was clean on disk and the project was freshly reloaded. 
[20220330_rename_move_package_rowan_walkback.txt](https://github.com/GemTalk/Rowan/files/8384048/20220330_rename_move_package_rowan_walkback.txt)

**Comment by ericwinger** [comment]
Think I see a problem.  I renamed the component to `common/tests/Tests/fnoodle` but what got written to disk when I exported it was `common/tests/common/tests/Tests/fnoodle`.  That doesn't seem correct. 
![image](https://user-images.githubusercontent.com/36212516/160933019-8075b676-0673-42ff-8b59-5493c2c52307.png)

**Comment by ericwinger** [comment]
I put a breakpoint in the rename to show what arguments I passed in: 
![image](https://user-images.githubusercontent.com/36212516/160933399-83c436be-847d-4495-8029-79b4a1bccb80.png)

**Comment by dalehenrich** [comment]
There's a comment in 2 of the three implementors `change the basename of aComponentPath to <baseName>, i.e., the path is not changed` ... I do realize that most of the time the full path is used so this one is worth discussing ... the use case I was convering  was where you could change the basename of the component (the use case I needed when I wrote the code) ... I would be inclined to use a message involving `move...` if you are actually changing the path for the component

**Comment by ericwinger** [comment]
After discussion with @dalehenrich Jadeite changed to only rename the tail of the component. Path is retained.
