### ISSUE TITLE
random 'projects up to date' error

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Rowan#82]
Randomly, I see a dialog popup saying that 'The projects are up to date.' Sometimes it happens on the method compile. 

This time, there was a subsequent error that allowed me to see a little of the stack. 

Where does this come from?   

![projectuptodate](https://user-images.githubusercontent.com/36212516/39022514-c1336966-43ea-11e8-9e9e-0e0c7449a3e3.jpg)

**Comment by dalehenrich** [comment]
I think that Jade occasionally (or all of the time?) does double compiles (when there is a Warning perhaps) and the second compile will almost always signal this ... Perhaps we should signal an explicit notification and in the places where Jade is doing a second compile (if that is what is going on), we can resume without `informing` the user ...

**Comment by dalehenrich** [comment]
bounce to @ericwinger ... @ericwinger will investigate double Jade compiles and/or try to get a stack or something more than anecdotal evidence so that we know where to look for a fix

**Comment by dalehenrich** [comment]
haven't seen this in a long time
