### ISSUE TITLE
Giant sparkle cursor (and remote performance)

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Rowan#84]
This is doubtless since I'm remote and the network round trips make operations take much longer than in-office... but this giant sparkle cursor shows up every time I click on a package, class, every method, every time.  They delay doesn't bother me, used to it from using GBS remotely.  But that sparkle is very distracting. 

This is also a heads up about performance over network.  Some examples (random results clicking around in Jadeite system browser):

server took 1ms; network took 512ms; client took 395ms; total of 908ms.
server took 32ms; network took 340ms; client took 8ms; total of 380ms.
server took 0ms; network took 784ms; client took 7ms; total of 791ms.
server took 1ms; network took 198ms; client took 442ms; total of 641ms.

I don't think this is an alpha issue.

**Comment by dalehenrich** [comment]
I think this was directly addressed by adding the Transcript switch ... further performance improvements is on the list
